#!/usr/bin/env bash

echo "JIT:"
$GRAALVM_HOME/bin/javac ClassLoader.java
$GRAALVM_HOME/bin/java ClassLoader resources

echo "native-image:"
$GRAALVM_HOME/bin/gu install native-image
$GRAALVM_HOME/bin/native-image ClassLoader
./classloader resources
